language: node_js

node_js:
  - "8"

git:
  depth: 1

env:
  global:
    - FIND_SH="find $TRAVIS_BUILD_DIR -name '*.sh' -type f -print0"
    - FIND_JSON="find $TRAVIS_BUILD_DIR -name '*.json' -type f -print0"
    - XARGS="xargs -0 -n1 -I {} -t"
    - BIN_DIR="$HOME/bin"
    - PATH="$BIN_DIR:$PATH"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script: eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: eval $FIND_SH | $XARGS shellcheck {}
    - stage: lint
      name: JSON Syntax Verification
      script: eval $FIND_JSON | $XARGS jq --exit-status . {} > /dev/null
    - stage: lint
      name: JSON Lint/Format Verification
      script: eval $FIND_JSON | $XARGS bash -c 'cmp {} <(jq --indent 4 -S . {})'
    - stage: lint
      name: Syntax Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make terraform/lint
        - make docs/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-inspector
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TARDIGRADE-INSPECTOR v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-inspector/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: Xdsvs5qNyqvE2j3RXEHQdmnTfpYMHdMFWcOtfKlxkIFyTLMxyWtyzj4qC0TpeQHBJU1DO3/Sm3+M9c22fOzhm87mjR3iuPDpswXXPj5q+6ip4KXS3GwzvhD74Rsl30a5e39a+HJNb57t1tqP8zDVGZp0avUUMi8RCEt8lN9RJ6HMnZqHFs7rZn7kipQAk7wxWnhnU2qcMZGd+Z7/MUyLI+OJsRbk+nDJqXNEjeeKmqP5kZ2iysD2hMNL7wYVq8j09ba28HEoTgljuTJixIRbFSQjRHfPYmnTtvqBCb8Wt4dt19AWd/Pvsf7Z9c+HaN91/tixhRVks64pFjqOPshBId6mhV/YGvRbN+XFyr6eCxuAetvGxgWOH9gGm+6NxrqnK8e7a0tvKBeZGVe/AXM2PSx9CiGGFs3fdSF+Boag0tHCXBPfPY/ByQt4vGaKwTdpeJAycXqG6Kbq2TbizpTekUM/B1R+3ZNdHiqB+5anoUgMR3pfrTDPF0OL2czqOixDOcUBRZIewBkoh3q4ociqlM6hqHAMnZ3byRCPpATpsLTQyqaqRxTzG4KkwoHCanha3APezHChReCk3pduG+s63qZ3ZsKvHAoYgGTVvY0CllkZJbVkAmby8PZVur+Vpu8NCfNX1CktdZLneA+SzdwjdjLnFoxSVbZU3F2eqlY2YIM=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-inspector
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
